package com.tenth.space.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.tenth.space.config.DBConstant;
import com.tenth.space.protobuf.helper.EntityChangeEngine;
import com.tenth.space.utils.Utils;

import java.util.Arrays;
import java.util.Objects;
/**
 * 这个类不同与其他自动生成代码
 * 需要依赖conten与display 依赖不同的状态
 */
// KEEP INCLUDES END
/**
 * Entity mapped to table Message.
 */
public class MessageEntity implements java.io.Serializable {

    protected Long id;
    protected int msgId;
    protected String fromId;
    protected String toId;
    /** Not-null value. */
    protected String sessionKey;
    /** Not-null value. */
    protected String content;
    protected String quoteContent;
    protected int msgType;
    protected int displayType;
    protected int status;
    protected int created;
    protected int updated;

    protected byte[] signHash;
    protected byte[] pubKey;
    protected int isVerifyOK = 0;
    // KEEP FIELDS - put your custom fields here

    protected boolean isGIfEmo;
    // KEEP FIELDS END

    public MessageEntity() {
    }

    public MessageEntity(Long id) {
        this.id = id;
    }

    public MessageEntity(Long id, int msgId, String fromId, String toId, String sessionKey, String content, int msgType, int displayType, int status, int created, int updated) {
        this.id = id;
        this.msgId = msgId;
        this.fromId = fromId;
        this.toId = toId;
        this.sessionKey = sessionKey;
        this.content = content;
        this.msgType = msgType;
        this.displayType = displayType;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public MessageEntity(Long id, int msgId, String fromId, String toId, String sessionKey, String content, int msgType, int displayType,
                         int status, int created, int updated, String signHash, int isVerifyOK) {
        this.id = id;
        this.msgId = msgId;
        this.fromId = fromId;
        this.toId = toId;
        this.sessionKey = sessionKey;
        this.content = content;
        this.msgType = msgType;
        this.displayType = displayType;
        this.status = status;
        this.created = created;
        this.updated = updated;
        this.signHash = Utils.hexStringToByteArray(signHash);
        this.isVerifyOK = isVerifyOK;
    }

    public MessageEntity(Long id, int msgId, String fromId, String toId, String sessionKey, String content, int msgType, int displayType,
                         int status, int created, int updated, String signHash, int isVerifyOK, String quoteContent) {
        this.id = id;
        this.msgId = msgId;
        this.fromId = fromId;
        this.toId = toId;
        this.sessionKey = sessionKey;
        this.content = content;
        this.msgType = msgType;
        this.displayType = displayType;
        this.status = status;
        this.created = created;
        this.updated = updated;
        this.signHash = Utils.hexStringToByteArray(signHash);
        this.isVerifyOK = isVerifyOK;
        this.quoteContent = quoteContent;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getMsgId() {
        return msgId;
    }

    public void setMsgId(int msgId) {
        this.msgId = msgId;
    }

    public String getFromId() {
        return fromId;
    }

    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    public String getToId() {
        return toId;
    }

    public void setToId(String toId) {
        this.toId = toId;
    }

    /** Not-null value. */
    public String getSessionKey() {
        return sessionKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public String getQuoteContent() {
        return quoteContent;
    }

    public String getSimpleShowQuoteContent() {
        String simpleShow = quoteContent;
        if(!Utils.isEmpty(simpleShow) && simpleShow.length() > 40)
            simpleShow = simpleShow.substring(0,40) + "...";

        return simpleShow;
    }

    public void setQuoteContent(String quoteContent) {
        this.quoteContent = quoteContent;
    }

    public int getMsgType() {
        return msgType;
    }

    public void setMsgType(int msgType) {
        this.msgType = msgType;
    }

    public int getDisplayType() {
        return displayType;
    }

    public void setDisplayType(int displayType) {
        this.displayType = displayType;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getCreated() {
        return created;
    }

    public void setCreated(int created) {
        this.created = created;
    }

    public int getUpdated() {
        return updated;
    }

    public void setUpdated(int updated) {
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here

    /**
     * -----根据自身状态判断的---------
     */
    public int getSessionType() {
        switch (msgType) {
            case DBConstant.MSG_TYPE_SINGLE_TEXT:
            case DBConstant.MSG_TYPE_SINGLE_AUDIO:
                return DBConstant.SESSION_TYPE_SINGLE;
            case DBConstant.MSG_TYPE_GROUP_TEXT:
            case DBConstant.MSG_TYPE_GROUP_AUDIO:
                return DBConstant.SESSION_TYPE_GROUP;
            default:
                //todo 有问题
                return DBConstant.SESSION_TYPE_SINGLE;
        }
    }


    public String getMessageDisplay() {
        switch (displayType) {
            case DBConstant.SHOW_AUDIO_TYPE:
                return DBConstant.DISPLAY_FOR_AUDIO;
            case DBConstant.SHOW_ORIGIN_TEXT_TYPE:
                return content;
            case DBConstant.SHOW_IMAGE_TYPE:
                return DBConstant.DISPLAY_FOR_IMAGE;
            case DBConstant.SHOW_MIX_TEXT:
                return DBConstant.DISPLAY_FOR_MIX;
            default:
                return DBConstant.DISPLAY_FOR_ERROR;
        }
    }

    @Override
    public String toString() {
        return "MessageEntity{" +
                "id=" + id +
                ", msgId=" + msgId +
                ", fromId='" + fromId + '\'' +
                ", toId='" + toId + '\'' +
                ", sessionKey='" + sessionKey + '\'' +
                ", content='" + content + '\'' +
                ", quoteContent='" + quoteContent + '\'' +
                ", msgType=" + msgType +
                ", displayType=" + displayType +
                ", status=" + status +
                ", created=" + created +
                ", updated=" + updated +
                ", signHash=" + Arrays.toString(signHash) +
                ", pubKey=" + Arrays.toString(pubKey) +
                ", isGIfEmo=" + isGIfEmo +
                '}';
    }

    /*
    @Override
    public String toString() {
        return "MessageEntity{" +
                "id=" + id +
                ", msgId=" + msgId +
                ", fromId=" + fromId +
                ", toId=" + toId +
                ", content='" + content + '\'' +
                ", msgType=" + msgType +
                ", displayType=" + displayType +
                ", status=" + status +
                ", created=" + created +
                ", updated=" + updated +
                '}';
    }

     */

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof MessageEntity))
            return false;

        MessageEntity that = (MessageEntity) o;

        if (created != that.created)
            return false;
        if (displayType != that.displayType)
            return false;
        if (fromId != that.fromId)
            return false;
        if (msgId != that.msgId)
            return false;
        if (msgType != that.msgType)
            return false;
        if (status != that.status)
            return false;
        if (toId != that.toId)
            return false;
        if (updated != that.updated)
            return false;
        if (!content.equals(that.content))
            return false;
        if (!id.equals(that.id))
            return false;
        if (!sessionKey.equals(that.sessionKey))
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = Objects.hash(id, msgId, fromId, toId, sessionKey, content, msgType, displayType, status, created, updated, isGIfEmo);
        result = 31 * result + Arrays.hashCode(signHash);
        result = 31 * result + Arrays.hashCode(pubKey);
        return result;
    }

    /*
    @Override
    public int hashCode() {
        int result = id.hashCode();
        result = 31 * result + msgId.has;
        result = 31 * result + fromId;
        result = 31 * result + toId;
        result = 31 * result + sessionKey.hashCode();
        result = 31 * result + content.hashCode();
        result = 31 * result + msgType;
        result = 31 * result + displayType;
        result = 31 * result + status;
        result = 31 * result + created;
        result = 31 * result + updated;
        return result;
    }


     */

    /**
     * 获取会话的sessionId
     * @param isSend
     * @return
     */
    public String getPeerId(boolean isSend) {
        if (isSend) {
            /**自己发出去的*/
            return toId;
        } else {
            /**接受到的*/
            switch (getSessionType()) {
                case DBConstant.SESSION_TYPE_SINGLE:
                    return fromId;
                case DBConstant.SESSION_TYPE_GROUP:
                    return toId;
                default:
                    return toId;
            }
        }
    }

    public byte[] getSendContent() {
        return null;
    }

    public void setSignHash(byte[] signHash) {
        this.signHash = signHash;
    }

    public void setSignHash(String signHash) {
        this.signHash = Utils.hexStringToByteArray(signHash);
    }

    public byte[] getSignHash(){
        if(null == signHash)
            setSignHash("ak");
        return signHash;
    }

    public void setPubKey(byte[] pubKey) {
        this.pubKey = pubKey;
    }

    public byte[] getPubKey(){
        return null;
    }

    public byte[] messageSerializeToStream(){
        return null;
    }

    public boolean verify(){
        return  false;
    }

    public boolean isGIfEmo() {
        return isGIfEmo;
    }

    public void setGIfEmo(boolean isGIfEmo) {
        this.isGIfEmo = isGIfEmo;
    }

    public boolean isSend(String loginId) {
        boolean isSend = (loginId.equals(fromId)) ? true : false;
        return isSend;
    }

    public String buildSessionKey(boolean isSend) {
        int sessionType = getSessionType();
        String peerId = getPeerId(isSend);
        sessionKey = EntityChangeEngine.getSessionKey(peerId, sessionType);
        return sessionKey;
    }
    // KEEP METHODS END


    public int getIsVerifyOK() {
        return isVerifyOK;
    }

    public void setIsVerifyOK(int isVerifyOK) {
        this.isVerifyOK = isVerifyOK;
    }
}
