package com.tenth.space.DB.dao;

import android.database.sqlite.SQLiteDatabase;

import com.tenth.space.DB.entity.BlogEntity;
import com.tenth.space.DB.entity.CommentEntity;
import com.tenth.space.DB.entity.DepartmentEntity;
import com.tenth.space.DB.entity.GroupEntity;
import com.tenth.space.DB.entity.GroupRequesterEntity;
import com.tenth.space.DB.entity.IdCardEntity;
import com.tenth.space.DB.entity.MessageEntity;
import com.tenth.space.DB.entity.RequesterEntity;
import com.tenth.space.DB.entity.SessionEntity;
import com.tenth.space.DB.entity.SysPushMsgEntity;
import com.tenth.space.DB.entity.UserEntity;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig departmentDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig groupDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig sessionDaoConfig;
    private final DaoConfig blogDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig requesterDaoConfig;
    private final DaoConfig groupRequesterDaoConfig;
    private final DaoConfig sysPushMsgDaoConfig;
    private final DaoConfig idCardDaoConfig;

    private final DepartmentDao departmentDao;
    private final UserDao userDao;
    private final GroupDao groupDao;
    private final MessageDao messageDao;
    private final SessionDao sessionDao;
    private final BlogDao blogDao;
    private final CommentDao commentDao;
    private final RequesterDao requesterDao;
    private final GroupRequesterDao groupRequesterDao;
    private final SysPushMsgDao sysPushMsgDao;
    private final IdCardDao idCardDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        departmentDaoConfig = daoConfigMap.get(DepartmentDao.class).clone();
        departmentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        blogDaoConfig = daoConfigMap.get(BlogDao.class).clone();
        blogDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        requesterDaoConfig = daoConfigMap.get(RequesterDao.class).clone();
        requesterDaoConfig.initIdentityScope(type);

        groupRequesterDaoConfig = daoConfigMap.get(GroupRequesterDao.class).clone();
        groupRequesterDaoConfig.initIdentityScope(type);

        sysPushMsgDaoConfig = daoConfigMap.get(SysPushMsgDao.class).clone();
        sysPushMsgDaoConfig.initIdentityScope(type);

        idCardDaoConfig = daoConfigMap.get(IdCardDao.class).clone();
        idCardDaoConfig.initIdentityScope(type);

        departmentDao = new DepartmentDao(departmentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);
        blogDao = new BlogDao(blogDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        requesterDao = new RequesterDao(requesterDaoConfig, this);
        groupRequesterDao = new GroupRequesterDao(groupRequesterDaoConfig, this);
        sysPushMsgDao = new SysPushMsgDao(sysPushMsgDaoConfig, this);
        idCardDao = new IdCardDao(idCardDaoConfig, this);

        registerDao(DepartmentEntity.class, departmentDao);
        registerDao(UserEntity.class, userDao);
        registerDao(GroupEntity.class, groupDao);
        registerDao(MessageEntity.class, messageDao);
        registerDao(SessionEntity.class, sessionDao);
        registerDao(BlogEntity.class, blogDao);
        registerDao(CommentEntity.class, commentDao);
        registerDao(RequesterEntity.class, requesterDao);
        registerDao(GroupRequesterEntity.class, groupRequesterDao);
        registerDao(SysPushMsgEntity.class, sysPushMsgDao);
        registerDao(IdCardEntity.class, idCardDao);
    }
    
    public void clear() {
        departmentDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        groupDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        sessionDaoConfig.getIdentityScope().clear();
        blogDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        requesterDaoConfig.getIdentityScope().clear();
        groupRequesterDaoConfig.getIdentityScope().clear();
        sysPushMsgDaoConfig.getIdentityScope().clear();
        idCardDaoConfig.getIdentityScope().clear();
    }

    public DepartmentDao getDepartmentDao() {
        return departmentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public BlogDao getBlogDao() {
        return blogDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public RequesterDao getRequesterDao() {
        return requesterDao;
    }

    public GroupRequesterDao getGroupRequesterDao() {
        return groupRequesterDao;
    }

    public SysPushMsgDao getSysPushMsgDao() {
        return sysPushMsgDao;
    }

    public IdCardDao getIdCardDao(){ return idCardDao;}

}
