package com.tenth.space.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.tenth.space.DB.entity.SysPushMsgEntity;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SysPushMsgInfo.
*/
public class SysPushMsgDao extends AbstractDao<SysPushMsgEntity, Long> {

    public static final String TABLENAME = "SysPushMsgInfo";

    /**
     * Properties of entity SysPushMsgEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Msg_type = new Property(0, Integer.class, "msg_type", false, "MSG_TYPE");
        public final static Property Id = new Property(1, Long.class, "id", true, "_id");
        public final static Property Avatar_url = new Property(2, String.class, "avatar_url", false, "AVATAR_URL");
        public final static Property Created = new Property(3, Long.class, "created", false, "CREATED");
        public final static Property IsRead = new Property(4, Boolean.class, "isRead", false, "IS_READ");
        public final static Property IsGroup = new Property(5, Boolean.class, "isGroup", false, "IS_GROUP");
        public final static Property Nick_name = new Property(6, String.class, "nick_name", false, "NICK_NAME");
        public final static Property FromUserId = new Property(7, int.class, "fromUserId", false, "FROM_USER_ID");
        public final static Property Addition_msg = new Property(8, String.class, "addition_msg", false, "ADDITION_MSG");
        public final static Property Agree_states = new Property(9, int.class, "agree_states", false, "AGREE_STATES");
    };


    public SysPushMsgDao(DaoConfig config) {
        super(config);
    }
    
    public SysPushMsgDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SysPushMsgInfo' (" + //
                "'MSG_TYPE' INTEGER," + // 0: msg_type
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 1: id
                "'AVATAR_URL' TEXT," + // 2: avatar_url
                "'CREATED' INTEGER," + // 3: created
                "'IS_READ' INTEGER," + // 4: isRead
                "'IS_GROUP' INTEGER," + // 5: isGroup
                "'NICK_NAME' TEXT NOT NULL ," + // 6: nick_name
                "'FROM_USER_ID' TEXT NOT NULL UNIQUE ," + // 7: fromUserId
                "'ADDITION_MSG' TEXT," + // 8: addition_msg
                "'AGREE_STATES' INTEGER NOT NULL );"); // 9: agree_states
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_SysPushMsgInfo_FROM_USER_ID ON SysPushMsgInfo" +
                " (FROM_USER_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SysPushMsgInfo'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SysPushMsgEntity entity) {
        stmt.clearBindings();
 
        Integer msg_type = entity.getMsg_type();
        if (msg_type != null) {
            stmt.bindLong(1, msg_type);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String avatar_url = entity.getAvatar_url();
        if (avatar_url != null) {
            stmt.bindString(3, avatar_url);
        }
 
        Long created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(4, created);
        }
 
        Boolean isRead = entity.getIsRead();
        if (isRead != null) {
            stmt.bindLong(5, isRead ? 1l: 0l);
        }
 
        Boolean isGroup = entity.getIsGroup();
        if (isGroup != null) {
            stmt.bindLong(6, isGroup ? 1l: 0l);
        }
        stmt.bindString(7, entity.getNick_name());
        stmt.bindString(8, entity.getFromUserId());
 
        String addition_msg = entity.getAddition_msg();
        if (addition_msg != null) {
            stmt.bindString(9, addition_msg);
        }
        stmt.bindLong(10, entity.getAgree_states());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public SysPushMsgEntity readEntity(Cursor cursor, int offset) {
        SysPushMsgEntity entity = new SysPushMsgEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // msg_type
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // avatar_url
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // created
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isRead
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // isGroup
            cursor.getString(offset + 6), // nick_name
            cursor.getString(offset + 7), // fromUserId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // addition_msg
            cursor.getInt(offset + 9) // agree_states
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SysPushMsgEntity entity, int offset) {
        entity.setMsg_type(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setAvatar_url(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreated(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIsRead(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setIsGroup(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setNick_name(cursor.getString(offset + 6));
        entity.setFromUserId(cursor.getString(offset + 7));
        entity.setAddition_msg(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setAgree_states(cursor.getInt(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SysPushMsgEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SysPushMsgEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
