// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Other.proto

package com.tenth.space.protobuf;

public final class IMOther {
  private IMOther() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Other.IMHeartBeat)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * <pre>
   *cmd id:  		0x0701
   * </pre>
   *
   * Protobuf type {@code IM.Other.IMHeartBeat}
   */
  public  static final class IMHeartBeat extends
      com.google.protobuf.GeneratedMessageLite<
          IMHeartBeat, IMHeartBeat.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Other.IMHeartBeat)
      IMHeartBeatOrBuilder {
    private IMHeartBeat() {
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.tenth.space.protobuf.IMOther.IMHeartBeat prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     *cmd id:  		0x0701
     * </pre>
     *
     * Protobuf type {@code IM.Other.IMHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.tenth.space.protobuf.IMOther.IMHeartBeat, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Other.IMHeartBeat)
        com.tenth.space.protobuf.IMOther.IMHeartBeatOrBuilder {
      // Construct using com.tenth.space.protobuf.IMOther.IMHeartBeat.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:IM.Other.IMHeartBeat)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.tenth.space.protobuf.IMOther.IMHeartBeat();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.tenth.space.protobuf.IMOther.IMHeartBeat> parser = PARSER;
          if (parser == null) {
            synchronized (com.tenth.space.protobuf.IMOther.IMHeartBeat.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.tenth.space.protobuf.IMOther.IMHeartBeat>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Other.IMHeartBeat)
    private static final com.tenth.space.protobuf.IMOther.IMHeartBeat DEFAULT_INSTANCE;
    static {
      IMHeartBeat defaultInstance = new IMHeartBeat();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IMHeartBeat.class, defaultInstance);
    }

    public static com.tenth.space.protobuf.IMOther.IMHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMHeartBeat> PARSER;

    public static com.google.protobuf.Parser<IMHeartBeat> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
