// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Register.proto

package com.tenth.space.protobuf;

public final class IMRegister {
  private IMRegister() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMRegisterReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Register.IMRegisterReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *cmd id:		0x0901
     * </pre>
     *
     * <code>string user_name = 1;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <pre>
     *cmd id:		0x0901
     * </pre>
     *
     * <code>string user_name = 1;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>bytes attach_data = 20;</code>
     * @return The attachData.
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Register.IMRegisterReq}
   */
  public  static final class IMRegisterReq extends
      com.google.protobuf.GeneratedMessageLite<
          IMRegisterReq, IMRegisterReq.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Register.IMRegisterReq)
      IMRegisterReqOrBuilder {
    private IMRegisterReq() {
      userName_ = "";
      password_ = "";
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int USER_NAME_FIELD_NUMBER = 1;
    private java.lang.String userName_;
    /**
     * <pre>
     *cmd id:		0x0901
     * </pre>
     *
     * <code>string user_name = 1;</code>
     * @return The userName.
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      return userName_;
    }
    /**
     * <pre>
     *cmd id:		0x0901
     * </pre>
     *
     * <code>string user_name = 1;</code>
     * @return The bytes for userName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userName_);
    }
    /**
     * <pre>
     *cmd id:		0x0901
     * </pre>
     *
     * <code>string user_name = 1;</code>
     * @param value The userName to set.
     */
    private void setUserName(
        java.lang.String value) {
      value.getClass();
  
      userName_ = value;
    }
    /**
     * <pre>
     *cmd id:		0x0901
     * </pre>
     *
     * <code>string user_name = 1;</code>
     */
    private void clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
    }
    /**
     * <pre>
     *cmd id:		0x0901
     * </pre>
     *
     * <code>string user_name = 1;</code>
     * @param value The bytes for userName to set.
     */
    private void setUserNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      userName_ = value.toStringUtf8();
      
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.String password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      return password_;
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>string password = 2;</code>
     * @param value The password to set.
     */
    private void setPassword(
        java.lang.String value) {
      value.getClass();
  
      password_ = value;
    }
    /**
     * <code>string password = 2;</code>
     */
    private void clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>string password = 2;</code>
     * @param value The bytes for password to set.
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      password_ = value.toStringUtf8();
      
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>bytes attach_data = 20;</code>
     * @return The attachData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }
    /**
     * <code>bytes attach_data = 20;</code>
     * @param value The attachData to set.
     */
    private void setAttachData(com.google.protobuf.ByteString value) {
      value.getClass();
  
      attachData_ = value;
    }
    /**
     * <code>bytes attach_data = 20;</code>
     */
    private void clearAttachData() {
      
      attachData_ = getDefaultInstance().getAttachData();
    }

    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.tenth.space.protobuf.IMRegister.IMRegisterReq prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code IM.Register.IMRegisterReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.tenth.space.protobuf.IMRegister.IMRegisterReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Register.IMRegisterReq)
        com.tenth.space.protobuf.IMRegister.IMRegisterReqOrBuilder {
      // Construct using com.tenth.space.protobuf.IMRegister.IMRegisterReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *cmd id:		0x0901
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @return The userName.
       */
      @java.lang.Override
      public java.lang.String getUserName() {
        return instance.getUserName();
      }
      /**
       * <pre>
       *cmd id:		0x0901
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @return The bytes for userName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        return instance.getUserNameBytes();
      }
      /**
       * <pre>
       *cmd id:		0x0901
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserName(value);
        return this;
      }
      /**
       * <pre>
       *cmd id:		0x0901
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        copyOnWrite();
        instance.clearUserName();
        return this;
      }
      /**
       * <pre>
       *cmd id:		0x0901
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserNameBytes(value);
        return this;
      }

      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      @java.lang.Override
      public java.lang.String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      /**
       * <code>bytes attach_data = 20;</code>
       * @return The attachData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAttachData() {
        return instance.getAttachData();
      }
      /**
       * <code>bytes attach_data = 20;</code>
       * @param value The attachData to set.
       * @return This builder for chaining.
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAttachData(value);
        return this;
      }
      /**
       * <code>bytes attach_data = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttachData() {
        copyOnWrite();
        instance.clearAttachData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Register.IMRegisterReq)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.tenth.space.protobuf.IMRegister.IMRegisterReq();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "userName_",
              "password_",
              "attachData_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0014\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0014\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.tenth.space.protobuf.IMRegister.IMRegisterReq> parser = PARSER;
          if (parser == null) {
            synchronized (com.tenth.space.protobuf.IMRegister.IMRegisterReq.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.tenth.space.protobuf.IMRegister.IMRegisterReq>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Register.IMRegisterReq)
    private static final com.tenth.space.protobuf.IMRegister.IMRegisterReq DEFAULT_INSTANCE;
    static {
      IMRegisterReq defaultInstance = new IMRegisterReq();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IMRegisterReq.class, defaultInstance);
    }

    public static com.tenth.space.protobuf.IMRegister.IMRegisterReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMRegisterReq> PARSER;

    public static com.google.protobuf.Parser<IMRegisterReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface IMRegisterRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Register.IMRegisterRsp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *cmd id:		0x0902
     * </pre>
     *
     * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
     * @return The enum numeric value on the wire for resultCode.
     */
    int getResultCodeValue();
    /**
     * <pre>
     *cmd id:		0x0902
     * </pre>
     *
     * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
     * @return The resultCode.
     */
    com.tenth.space.protobuf.IMBaseDefine.ResultType getResultCode();

    /**
     * <code>string result_string = 2;</code>
     * @return The resultString.
     */
    java.lang.String getResultString();
    /**
     * <code>string result_string = 2;</code>
     * @return The bytes for resultString.
     */
    com.google.protobuf.ByteString
        getResultStringBytes();

    /**
     * <code>bytes attach_data = 20;</code>
     * @return The attachData.
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Register.IMRegisterRsp}
   */
  public  static final class IMRegisterRsp extends
      com.google.protobuf.GeneratedMessageLite<
          IMRegisterRsp, IMRegisterRsp.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.Register.IMRegisterRsp)
      IMRegisterRspOrBuilder {
    private IMRegisterRsp() {
      resultString_ = "";
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int RESULT_CODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <pre>
     *cmd id:		0x0902
     * </pre>
     *
     * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
     * @return The enum numeric value on the wire for resultCode.
     */
    @java.lang.Override
    public int getResultCodeValue() {
      return resultCode_;
    }
    /**
     * <pre>
     *cmd id:		0x0902
     * </pre>
     *
     * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
     * @return The resultCode.
     */
    @java.lang.Override
    public com.tenth.space.protobuf.IMBaseDefine.ResultType getResultCode() {
      com.tenth.space.protobuf.IMBaseDefine.ResultType result = com.tenth.space.protobuf.IMBaseDefine.ResultType.forNumber(resultCode_);
      return result == null ? com.tenth.space.protobuf.IMBaseDefine.ResultType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *cmd id:		0x0902
     * </pre>
     *
     * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
     * @param value The enum numeric value on the wire for resultCode to set.
     */
    private void setResultCodeValue(int value) {
        resultCode_ = value;
    }
    /**
     * <pre>
     *cmd id:		0x0902
     * </pre>
     *
     * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
     * @param value The resultCode to set.
     */
    private void setResultCode(com.tenth.space.protobuf.IMBaseDefine.ResultType value) {
      resultCode_ = value.getNumber();
      
    }
    /**
     * <pre>
     *cmd id:		0x0902
     * </pre>
     *
     * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
     */
    private void clearResultCode() {
      
      resultCode_ = 0;
    }

    public static final int RESULT_STRING_FIELD_NUMBER = 2;
    private java.lang.String resultString_;
    /**
     * <code>string result_string = 2;</code>
     * @return The resultString.
     */
    @java.lang.Override
    public java.lang.String getResultString() {
      return resultString_;
    }
    /**
     * <code>string result_string = 2;</code>
     * @return The bytes for resultString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultStringBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(resultString_);
    }
    /**
     * <code>string result_string = 2;</code>
     * @param value The resultString to set.
     */
    private void setResultString(
        java.lang.String value) {
      value.getClass();
  
      resultString_ = value;
    }
    /**
     * <code>string result_string = 2;</code>
     */
    private void clearResultString() {
      
      resultString_ = getDefaultInstance().getResultString();
    }
    /**
     * <code>string result_string = 2;</code>
     * @param value The bytes for resultString to set.
     */
    private void setResultStringBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      resultString_ = value.toStringUtf8();
      
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>bytes attach_data = 20;</code>
     * @return The attachData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }
    /**
     * <code>bytes attach_data = 20;</code>
     * @param value The attachData to set.
     */
    private void setAttachData(com.google.protobuf.ByteString value) {
      value.getClass();
  
      attachData_ = value;
    }
    /**
     * <code>bytes attach_data = 20;</code>
     */
    private void clearAttachData() {
      
      attachData_ = getDefaultInstance().getAttachData();
    }

    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.tenth.space.protobuf.IMRegister.IMRegisterRsp prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code IM.Register.IMRegisterRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.tenth.space.protobuf.IMRegister.IMRegisterRsp, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.Register.IMRegisterRsp)
        com.tenth.space.protobuf.IMRegister.IMRegisterRspOrBuilder {
      // Construct using com.tenth.space.protobuf.IMRegister.IMRegisterRsp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *cmd id:		0x0902
       * </pre>
       *
       * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
       * @return The enum numeric value on the wire for resultCode.
       */
      @java.lang.Override
      public int getResultCodeValue() {
        return instance.getResultCodeValue();
      }
      /**
       * <pre>
       *cmd id:		0x0902
       * </pre>
       *
       * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
       * @param value The resultCode to set.
       * @return This builder for chaining.
       */
      public Builder setResultCodeValue(int value) {
        copyOnWrite();
        instance.setResultCodeValue(value);
        return this;
      }
      /**
       * <pre>
       *cmd id:		0x0902
       * </pre>
       *
       * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
       * @return The resultCode.
       */
      @java.lang.Override
      public com.tenth.space.protobuf.IMBaseDefine.ResultType getResultCode() {
        return instance.getResultCode();
      }
      /**
       * <pre>
       *cmd id:		0x0902
       * </pre>
       *
       * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
       * @param value The enum numeric value on the wire for resultCode to set.
       * @return This builder for chaining.
       */
      public Builder setResultCode(com.tenth.space.protobuf.IMBaseDefine.ResultType value) {
        copyOnWrite();
        instance.setResultCode(value);
        return this;
      }
      /**
       * <pre>
       *cmd id:		0x0902
       * </pre>
       *
       * <code>.IM.BaseDefine.ResultType result_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultCode() {
        copyOnWrite();
        instance.clearResultCode();
        return this;
      }

      /**
       * <code>string result_string = 2;</code>
       * @return The resultString.
       */
      @java.lang.Override
      public java.lang.String getResultString() {
        return instance.getResultString();
      }
      /**
       * <code>string result_string = 2;</code>
       * @return The bytes for resultString.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getResultStringBytes() {
        return instance.getResultStringBytes();
      }
      /**
       * <code>string result_string = 2;</code>
       * @param value The resultString to set.
       * @return This builder for chaining.
       */
      public Builder setResultString(
          java.lang.String value) {
        copyOnWrite();
        instance.setResultString(value);
        return this;
      }
      /**
       * <code>string result_string = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultString() {
        copyOnWrite();
        instance.clearResultString();
        return this;
      }
      /**
       * <code>string result_string = 2;</code>
       * @param value The bytes for resultString to set.
       * @return This builder for chaining.
       */
      public Builder setResultStringBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResultStringBytes(value);
        return this;
      }

      /**
       * <code>bytes attach_data = 20;</code>
       * @return The attachData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAttachData() {
        return instance.getAttachData();
      }
      /**
       * <code>bytes attach_data = 20;</code>
       * @param value The attachData to set.
       * @return This builder for chaining.
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAttachData(value);
        return this;
      }
      /**
       * <code>bytes attach_data = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttachData() {
        copyOnWrite();
        instance.clearAttachData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Register.IMRegisterRsp)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.tenth.space.protobuf.IMRegister.IMRegisterRsp();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "resultCode_",
              "resultString_",
              "attachData_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0014\u0003\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "\u0014\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.tenth.space.protobuf.IMRegister.IMRegisterRsp> parser = PARSER;
          if (parser == null) {
            synchronized (com.tenth.space.protobuf.IMRegister.IMRegisterRsp.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.tenth.space.protobuf.IMRegister.IMRegisterRsp>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.Register.IMRegisterRsp)
    private static final com.tenth.space.protobuf.IMRegister.IMRegisterRsp DEFAULT_INSTANCE;
    static {
      IMRegisterRsp defaultInstance = new IMRegisterRsp();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IMRegisterRsp.class, defaultInstance);
    }

    public static com.tenth.space.protobuf.IMRegister.IMRegisterRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMRegisterRsp> PARSER;

    public static com.google.protobuf.Parser<IMRegisterRsp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
