// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.SwitchService.proto

package com.tenth.space.protobuf;

public final class IMSwitchService {
  private IMSwitchService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMP2PCmdMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.SwitchService.IMP2PCmdMsg)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>uint32 from_user_id = 1;</code>
     * @return The fromUserId.
     */
    int getFromUserId();

    /**
     * <code>uint32 to_user_id = 2;</code>
     * @return The toUserId.
     */
    int getToUserId();

    /**
     * <code>string cmd_msg_data = 3;</code>
     * @return The cmdMsgData.
     */
    java.lang.String getCmdMsgData();
    /**
     * <code>string cmd_msg_data = 3;</code>
     * @return The bytes for cmdMsgData.
     */
    com.google.protobuf.ByteString
        getCmdMsgDataBytes();
  }
  /**
   * Protobuf type {@code IM.SwitchService.IMP2PCmdMsg}
   */
  public  static final class IMP2PCmdMsg extends
      com.google.protobuf.GeneratedMessageLite<
          IMP2PCmdMsg, IMP2PCmdMsg.Builder> implements
      // @@protoc_insertion_point(message_implements:IM.SwitchService.IMP2PCmdMsg)
      IMP2PCmdMsgOrBuilder {
    private IMP2PCmdMsg() {
      cmdMsgData_ = "";
    }
    public static final int FROM_USER_ID_FIELD_NUMBER = 1;
    private int fromUserId_;
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>uint32 from_user_id = 1;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public int getFromUserId() {
      return fromUserId_;
    }
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>uint32 from_user_id = 1;</code>
     * @param value The fromUserId to set.
     */
    private void setFromUserId(int value) {
      
      fromUserId_ = value;
    }
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>uint32 from_user_id = 1;</code>
     */
    private void clearFromUserId() {
      
      fromUserId_ = 0;
    }

    public static final int TO_USER_ID_FIELD_NUMBER = 2;
    private int toUserId_;
    /**
     * <code>uint32 to_user_id = 2;</code>
     * @return The toUserId.
     */
    @java.lang.Override
    public int getToUserId() {
      return toUserId_;
    }
    /**
     * <code>uint32 to_user_id = 2;</code>
     * @param value The toUserId to set.
     */
    private void setToUserId(int value) {
      
      toUserId_ = value;
    }
    /**
     * <code>uint32 to_user_id = 2;</code>
     */
    private void clearToUserId() {
      
      toUserId_ = 0;
    }

    public static final int CMD_MSG_DATA_FIELD_NUMBER = 3;
    private java.lang.String cmdMsgData_;
    /**
     * <code>string cmd_msg_data = 3;</code>
     * @return The cmdMsgData.
     */
    @java.lang.Override
    public java.lang.String getCmdMsgData() {
      return cmdMsgData_;
    }
    /**
     * <code>string cmd_msg_data = 3;</code>
     * @return The bytes for cmdMsgData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdMsgDataBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cmdMsgData_);
    }
    /**
     * <code>string cmd_msg_data = 3;</code>
     * @param value The cmdMsgData to set.
     */
    private void setCmdMsgData(
        java.lang.String value) {
      value.getClass();
  
      cmdMsgData_ = value;
    }
    /**
     * <code>string cmd_msg_data = 3;</code>
     */
    private void clearCmdMsgData() {
      
      cmdMsgData_ = getDefaultInstance().getCmdMsgData();
    }
    /**
     * <code>string cmd_msg_data = 3;</code>
     * @param value The bytes for cmdMsgData to set.
     */
    private void setCmdMsgDataBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      cmdMsgData_ = value.toStringUtf8();
      
    }

    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code IM.SwitchService.IMP2PCmdMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg, Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.SwitchService.IMP2PCmdMsg)
        com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsgOrBuilder {
      // Construct using com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>uint32 from_user_id = 1;</code>
       * @return The fromUserId.
       */
      @java.lang.Override
      public int getFromUserId() {
        return instance.getFromUserId();
      }
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>uint32 from_user_id = 1;</code>
       * @param value The fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserId(int value) {
        copyOnWrite();
        instance.setFromUserId(value);
        return this;
      }
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>uint32 from_user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUserId() {
        copyOnWrite();
        instance.clearFromUserId();
        return this;
      }

      /**
       * <code>uint32 to_user_id = 2;</code>
       * @return The toUserId.
       */
      @java.lang.Override
      public int getToUserId() {
        return instance.getToUserId();
      }
      /**
       * <code>uint32 to_user_id = 2;</code>
       * @param value The toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserId(int value) {
        copyOnWrite();
        instance.setToUserId(value);
        return this;
      }
      /**
       * <code>uint32 to_user_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUserId() {
        copyOnWrite();
        instance.clearToUserId();
        return this;
      }

      /**
       * <code>string cmd_msg_data = 3;</code>
       * @return The cmdMsgData.
       */
      @java.lang.Override
      public java.lang.String getCmdMsgData() {
        return instance.getCmdMsgData();
      }
      /**
       * <code>string cmd_msg_data = 3;</code>
       * @return The bytes for cmdMsgData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCmdMsgDataBytes() {
        return instance.getCmdMsgDataBytes();
      }
      /**
       * <code>string cmd_msg_data = 3;</code>
       * @param value The cmdMsgData to set.
       * @return This builder for chaining.
       */
      public Builder setCmdMsgData(
          java.lang.String value) {
        copyOnWrite();
        instance.setCmdMsgData(value);
        return this;
      }
      /**
       * <code>string cmd_msg_data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdMsgData() {
        copyOnWrite();
        instance.clearCmdMsgData();
        return this;
      }
      /**
       * <code>string cmd_msg_data = 3;</code>
       * @param value The bytes for cmdMsgData to set.
       * @return This builder for chaining.
       */
      public Builder setCmdMsgDataBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCmdMsgDataBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.SwitchService.IMP2PCmdMsg)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "fromUserId_",
              "toUserId_",
              "cmdMsgData_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg> parser = PARSER;
          if (parser == null) {
            synchronized (com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:IM.SwitchService.IMP2PCmdMsg)
    private static final com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg DEFAULT_INSTANCE;
    static {
      IMP2PCmdMsg defaultInstance = new IMP2PCmdMsg();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IMP2PCmdMsg.class, defaultInstance);
    }

    public static com.tenth.space.protobuf.IMSwitchService.IMP2PCmdMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IMP2PCmdMsg> PARSER;

    public static com.google.protobuf.Parser<IMP2PCmdMsg> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
